export const DEFAULT_PORT = 9786;
export const CONNECT_REFUSED = 'ECONNREFUSED';

export const ENV_CRON = 'AOMEX_CRON';
export const ENV_CRON_SCHEDULE_TIME = 'AOMEX_CRON_SCHEDULE_TIME';
export const ENV_CRON_EXECUTION_TIME = 'AOMEX_CRON_EXECUTION_TIME';
export const ENV_CRON_NEXT_SCHEDULE_TIME = 'AOMEX_CRON_NEXT_SCHEDULE_TIME';

export const TELL_CHILD_STOP = 'CRON_CHILD_STOP';
export const TELL_PARENT_INIT = 'CRON_PARENT_INIT';
export const TELL_CHILD_RESOLVE = 'CRON_CHILD_RESOLVE';
export const TELL_CHILD_REJECT = 'CRON_CHILD_REJECT';
