name: Lint

on: [push]

jobs:
  git-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'
      - run: pnpm install
      - if: github.event_name == 'pull_request'
        run: pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - if: github.event_name == 'push'
        run: echo "${{ github.event.head_commit.message }}" | pnpm exec commitlint --verbose
  type-checking:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 暂时没有 @types/node@22.x
        node-dts: [20.x]
        ts: [5.4.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'
      - name: Use Typescript@${{ matrix.ts }} & @types/node@${{ matrix.node-dts }}
        run: |
          pnpm install
          pnpm install @types/node@${{ matrix.node-dts }} typescript@${{ matrix.ts }} -w
      - run: pnpm exec tsc
  code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'
      - run: pnpm install
      - run: pnpm exec prettier --cache --check .
  bundle:
    needs: [git-commit, type-checking, code-format]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['20.13.0', 20.x, 22.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'
      - run: pnpm install
      - run: pnpm build
