name: Release

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'
      - run: pnpm install
      - name: Create PR or Publish
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version
          publish: pnpm run ci:publish
          commit: 'chore(release): bump version'
          title: 'Release version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
