name: Test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['20.13.0', 20.x, '22.0', 22.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          # node20 + ubuntu使用缓存导致redis-server安装失败
          # cache: 'pnpm'
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm test
      - if: github.ref == 'refs/heads/main' && strategy.job-index == 0
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
